import { defineConfig } from 'drizzle-kit';

/**
 * Drizzle config.
 * - Schema: ./drizzle/schema.ts
 * - Migrations: ./supabase/migrations (Supabase convention)
 * - DB connection: DATABASE_URL ב-.env.local
 *
 * Note: SQL migrations are hand-written (raw SQL) for pgvector + RLS support,
 * not auto-generated by drizzle-kit. The schema.ts file is for type-safe
 * queries only — apply migrations via Supabase SQL Editor.
 */
export default defineConfig({
  schema: './drizzle/schema.ts',
  out: './supabase/migrations',
  dialect: 'postgresql',
  dbCredentials: {
    url: process.env.DATABASE_URL!,
  },
  verbose: true,
  strict: true,
});
